defmodule Zed.Cluster do
  @moduledoc """
  Manage connections to remote Zed agents and execute operations.

  All remote operations use `:rpc.call` to the `Zed.Agent` GenServer
  running on each node. The Erlang cookie provides authentication.

  ## Connecting to Nodes

      # Connect to a single node
      Zed.Cluster.connect(:"zed@host2.local")

      # Connect to multiple nodes
      Zed.Cluster.connect_all([:"zed@host1", :"zed@host2", :"zed@host3"])

      # List connected nodes
      Zed.Cluster.nodes()

  ## Remote Operations

      # Run converge on remote node
      Zed.Cluster.converge(:"zed@host2", ir)
      Zed.Cluster.converge(:"zed@host2", ir, dry_run: true)

      # Get diff from remote
      Zed.Cluster.diff(:"zed@host2", ir)

      # Get status from remote
      Zed.Cluster.status(:"zed@host2", ir)

      # Rollback on remote
      Zed.Cluster.rollback(:"zed@host2", ir, "@latest")

  ## Multi-Node Operations

      # Converge on all connected nodes
      Zed.Cluster.converge_all(ir)

      # Get status from all nodes
      Zed.Cluster.status_all(ir)
  """

  require Logger

  @rpc_timeout 60_000

  # --- Connection Management ---

  @doc "Connect to a remote node."
  def connect(node) when is_atom(node) do
    case Node.connect(node) do
      true ->
        Logger.info("[Zed.Cluster] Connected to #{node}")
        :ok

      false ->
        {:error, :connection_failed}

      :ignored ->
        {:error, :not_distributed}
    end
  end

  @doc "Connect to multiple nodes. Returns map of results."
  def connect_all(nodes) when is_list(nodes) do
    nodes
    |> Enum.map(fn node -> {node, connect(node)} end)
    |> Map.new()
  end

  @doc "List connected Zed nodes (nodes with Zed.Agent running)."
  def nodes do
    Node.list()
    |> Enum.filter(&agent_running?/1)
  end

  @doc "List all connected Erlang nodes."
  def all_nodes do
    Node.list()
  end

  @doc "Check if Zed.Agent is running on a node."
  def agent_running?(node) do
    case ping(node) do
      {:pong, _} -> true
      _ -> false
    end
  end

  # --- Remote Operations ---

  @doc "Ping remote agent."
  def ping(node) do
    rpc_call(node, Zed.Agent, :ping, [])
  end

  @doc "Get agent info from remote node."
  def info(node) do
    rpc_call(node, Zed.Agent, :info, [])
  end

  @doc "Run converge on remote node."
  def converge(node, ir, opts \\ []) do
    rpc_call(node, Zed.Agent, :converge, [ir, opts], :infinity)
  end

  @doc "Compute diff on remote node."
  def diff(node, ir) do
    rpc_call(node, Zed.Agent, :diff, [ir])
  end

  @doc "Get status from remote node."
  def status(node, ir) do
    rpc_call(node, Zed.Agent, :status, [ir])
  end

  @doc "Rollback on remote node."
  def rollback(node, ir, target) do
    rpc_call(node, Zed.Agent, :rollback, [ir, target], :infinity)
  end

  # --- Multi-Node Operations ---

  @doc "Converge on all connected nodes. Returns map of {node, result}."
  def converge_all(ir, opts \\ []) do
    nodes()
    |> Task.async_stream(
      fn node -> {node, converge(node, ir, opts)} end,
      timeout: :infinity,
      ordered: false
    )
    |> Enum.map(fn {:ok, result} -> result end)
    |> Map.new()
  end

  @doc "Get status from all connected nodes."
  def status_all(ir) do
    nodes()
    |> Task.async_stream(
      fn node -> {node, status(node, ir)} end,
      timeout: @rpc_timeout
    )
    |> Enum.map(fn {:ok, result} -> result end)
    |> Map.new()
  end

  @doc "Get diff from all connected nodes."
  def diff_all(ir) do
    nodes()
    |> Task.async_stream(
      fn node -> {node, diff(node, ir)} end,
      timeout: @rpc_timeout
    )
    |> Enum.map(fn {:ok, result} -> result end)
    |> Map.new()
  end

  @doc """
  Coordinated converge across multiple hosts with rollback on failure.

  Implements the 2-phase protocol from `specs/CoordinatedConverge.tla`:

  1. **Snapshot** all hosts before any changes
  2. **Converge** each host (may succeed or fail independently)
  3. **If ALL succeed** → done. **If ANY fail** → rollback ALL to
     pre-converge snapshot.

  Safety invariant (NoPartialState): at return, either all hosts are
  converged or all are rolled back. No partial state.

  ## Options

  - `:host_irs` — list of `{host_name, node, ir}` tuples. Each host
    gets its own IR with its own pool. Generated by the `host` DSL verb.
  - `:nodes` — fallback: list of nodes, all get the same `ir`.
  - `:timeout` — per-host RPC timeout (default: infinity).

  ## Returns

  - `{:ok, %{host => result}}` — all hosts converged successfully.
  - `{:error, :snapshot_failed, details}` — couldn't snapshot a host.
  - `{:error, :partial_failure, %{failed: [...], rolled_back: [...]}}` —
    some hosts failed, all rolled back to pre-converge state.
  """
  def converge_coordinated(ir, opts \\ []) do
    host_irs = Keyword.get(opts, :host_irs)

    targets =
      if host_irs do
        # From DSL host verb: each host has its own IR + pool
        Enum.map(host_irs, fn {name, node_name, host_ir} ->
          %{name: name, node: node_name, ir: host_ir}
        end)
      else
        # Fallback: all connected nodes get the same IR
        target_nodes = Keyword.get(opts, :nodes, nodes())
        Enum.map(target_nodes, fn node_name ->
          %{name: node_name, node: node_name, ir: ir}
        end)
      end

    if targets == [] do
      {:error, :no_targets}
    else
      do_coordinated_converge(targets, opts)
    end
  end

  # ---------------------------------------------------------------
  # 2-phase coordinated converge (matches TLA+ spec)
  # ---------------------------------------------------------------

  defp do_coordinated_converge(targets, opts) do
    Logger.info("[Zed.Cluster] coordinated converge: #{length(targets)} hosts")

    # Phase 1: Snapshot all hosts
    case snapshot_all(targets) do
      {:ok, snapshots} ->
        Logger.info("[Zed.Cluster] phase 1 (snapshot): #{map_size(snapshots)} hosts snapshotted")

        # Phase 2: Converge all hosts
        results = converge_all_targets(targets, opts)

        succeeded = Enum.filter(results, fn {_, r} -> match?({:ok, _}, r) end)
        failed = Enum.filter(results, fn {_, r} -> not match?({:ok, _}, r) end)

        if failed == [] do
          # All succeeded → done
          Logger.info("[Zed.Cluster] phase 2 (converge): all #{length(succeeded)} hosts succeeded")
          {:ok, Map.new(results)}
        else
          # Some failed → Phase 3: rollback ALL to pre-converge snapshots
          Logger.warning("[Zed.Cluster] phase 2 (converge): #{length(failed)} failed, rolling back all")
          rollback_results = rollback_all(targets, snapshots)

          {:error, :partial_failure, %{
            failed: Enum.map(failed, fn {name, err} -> {name, err} end),
            rolled_back: rollback_results,
            snapshots: snapshots
          }}
        end

      {:error, _} = err ->
        Logger.error("[Zed.Cluster] phase 1 (snapshot) failed: #{inspect(err)}")
        err
    end
  end

  # Phase 1: snapshot every host's datasets
  defp snapshot_all(targets) do
    ts = timestamp()

    results =
      Enum.map(targets, fn %{name: name, node: node_name, ir: host_ir} ->
        snap_name = "zed-coordinated-#{ts}"

        result =
          Enum.map(host_ir.datasets, fn dataset_node ->
            full_path = "#{host_ir.pool}/#{dataset_node.id}"
            snap = "#{full_path}@#{snap_name}"

            if node_name == node() do
              # Local
              Zed.ZFS.Snapshot.create(full_path, snap_name)
              snap
            else
              # Remote
              case rpc_call(node_name, Zed.ZFS.Snapshot, :create, [full_path, snap_name], @rpc_timeout) do
                {:ok, _} -> snap
                {:error, _, _} = err -> err
                err -> {:error, :snapshot_failed, err}
              end
            end
          end)

        errors = Enum.filter(result, &match?({:error, _, _}, &1))

        if errors == [] do
          {name, result}
        else
          {name, {:error, errors}}
        end
      end)

    snapshot_failures = Enum.filter(results, fn {_, v} -> match?({:error, _}, v) end)

    if snapshot_failures == [] do
      {:ok, Map.new(results)}
    else
      {:error, :snapshot_failed, snapshot_failures}
    end
  end

  # Phase 2: converge all targets
  defp converge_all_targets(targets, opts) do
    Enum.map(targets, fn %{name: name, node: node_name, ir: host_ir} ->
      result =
        if node_name == node() do
          Zed.Converge.run(host_ir, opts)
        else
          case rpc_call(node_name, Zed.Converge, :run, [host_ir, opts], :infinity) do
            {:badrpc, reason} -> {:error, :rpc_failed, reason}
            result -> result
          end
        end

      {name, result}
    end)
  end

  # Phase 3: rollback ALL hosts to pre-converge snapshots
  defp rollback_all(targets, snapshots) do
    Enum.map(targets, fn %{name: name, node: node_name, ir: host_ir} ->
      snap_list = Map.get(snapshots, name, [])

      results =
        Enum.map(snap_list, fn
          snap when is_binary(snap) ->
            if node_name == node() do
              Zed.ZFS.Snapshot.rollback(snap)
            else
              rpc_call(node_name, Zed.ZFS.Snapshot, :rollback, [snap], @rpc_timeout)
            end

          other ->
            {:skip, other}
        end)

      {name, results}
    end)
    |> Map.new()
  end

  defp timestamp do
    {{y, m, d}, {h, min, s}} = :calendar.universal_time()
    :io_lib.format("~4..0B~2..0B~2..0BT~2..0B~2..0B~2..0B", [y, m, d, h, min, s])
    |> IO.iodata_to_binary()
  end

  # --- Private ---

  defp rpc_call(node, module, function, args, timeout \\ @rpc_timeout) do
    case :rpc.call(node, module, function, args, timeout) do
      {:badrpc, reason} ->
        {:error, {:rpc_failed, node, reason}}

      result ->
        result
    end
  end
end
