defmodule Zed.Secrets.Verify do
  @moduledoc """
  Password verification for slots generated by `Zed.Secrets.Generate`.

  Parses the PHC-formatted string produced by `pbkdf2_sha256/2`,
  recomputes the hash under the stored salt + iteration count, and
  constant-time-compares the result.
  """

  @doc """
  Verify `plaintext` against a stored PBKDF2-SHA256 PHC hash.

  Returns `true` on match, `false` on mismatch or any parse failure.
  Never raises.
  """
  def password(plaintext, stored_hash) when is_binary(plaintext) and is_binary(stored_hash) do
    verify_pbkdf2(plaintext, stored_hash)
  rescue
    _ -> false
  end

  def password(_, _), do: false

  defp verify_pbkdf2(plaintext, "$pbkdf2-sha256$i=" <> rest) do
    [iters_str, salt_b64, hash_b64] = String.split(rest, "$", parts: 3)

    iters = String.to_integer(iters_str)
    salt = Base.decode64!(salt_b64, padding: false)
    expected = Base.decode64!(hash_b64, padding: false)
    actual = :crypto.pbkdf2_hmac(:sha256, plaintext, salt, iters, byte_size(expected))

    constant_time_equal?(actual, expected)
  end

  defp verify_pbkdf2(_, _), do: false

  defp constant_time_equal?(a, b) when byte_size(a) != byte_size(b), do: false

  defp constant_time_equal?(a, b) do
    :crypto.exor(a, b)
    |> :binary.bin_to_list()
    |> Enum.reduce(0, &Bitwise.bor/2)
    |> Kernel.==(0)
  end
end
