defmodule Zed.Examples.SmokeContainedRealSecrets do
  @moduledoc """
  Path C6 smoke: two jails running hello_beam, both cookies resolved
  from `{:secret, :beam_cookie}` — an encrypted ZFS-backed secret
  slot generated by `Zed.Bootstrap.init`. No `SMOKE_COOKIE` in the
  operator's environment; the cookie value never touches an env var.

  Prereq: run `scripts/bootstrap-secrets.sh` once on mac-248 to
  generate `mac_zroot/zed` + `mac_zroot/zed/secrets` and stamp per-
  slot ZFS properties.

  Two jails (10.17.89.95..96) so the smoke is quick to bring up,
  quick to tear down, and easy to reason about; the machinery
  scales identically to C5's five nodes.

  ## Usage on mac-248

      # One-time (idempotent)
      BOOTSTRAP_PASSPHRASE=smoke-c6-pass \\
        sh scripts/bootstrap-secrets.sh

      sh scripts/build-real-release.sh
      sh scripts/smoke-contained-real-secrets.sh clean

      doas mix run -e \\
        "IO.inspect(Zed.Examples.SmokeContainedRealSecrets.converge(), limit: :infinity)"

      sh scripts/smoke-contained-real-secrets.sh verify
  """

  use Zed.DSL

  deploy :smoke_contained_real_secrets, pool: "mac_zroot" do
    dataset "jails/hello_beam_a95" do
      compression :lz4
    end

    dataset "jails/hello_beam_a96" do
      compression :lz4
    end

    app :hello_beam_a95 do
      dataset "jails/hello_beam_a95"
      version "0.1.0"
      release_path "/var/tmp/zed-smoke/hello_beam-0.1.0.tar.gz"
      mount_in_jail "/opt/hello_beam"
      service :hello_beam
      env_file "/var/db/zed/hello_beam.env"
      node_name :"hello_beam@10.17.89.95"

      # THE POINT of Path C6: cookie resolves from the encrypted
      # secrets dataset via ZFS-property lookup, not from an env var.
      cookie {:secret, :beam_cookie}

      health :tcp, host: "10.17.89.95", port: 4369, timeout: 3000, attempts: 15, interval: 1000

      health :beam_ping,
        node: :"hello_beam@10.17.89.95",
        cookie: {:secret, :beam_cookie},
        timeout: 5000,
        attempts: 20,
        interval: 1000
    end

    app :hello_beam_a96 do
      dataset "jails/hello_beam_a96"
      version "0.1.0"
      release_path "/var/tmp/zed-smoke/hello_beam-0.1.0.tar.gz"
      mount_in_jail "/opt/hello_beam"
      service :hello_beam
      env_file "/var/db/zed/hello_beam.env"
      node_name :"hello_beam@10.17.89.96"
      cookie {:secret, :beam_cookie}

      health :tcp, host: "10.17.89.96", port: 4369, timeout: 3000, attempts: 15, interval: 1000

      health :beam_ping,
        node: :"hello_beam@10.17.89.96",
        cookie: {:secret, :beam_cookie},
        timeout: 5000,
        attempts: 20,
        interval: 1000
    end

    jail :hello_beam_a95 do
      dataset "jails/hello_beam_a95"
      hostname "hello-beam-a95.local"
      ip4 "10.17.89.95/24"
      release "15.0-RELEASE"
      contains :hello_beam_a95
      nullfs_mount "/var/db/zed/cluster", into: "/var/db/zed/cluster", mode: :ro
    end

    jail :hello_beam_a96 do
      dataset "jails/hello_beam_a96"
      hostname "hello-beam-a96.local"
      ip4 "10.17.89.96/24"
      release "15.0-RELEASE"
      contains :hello_beam_a96
      nullfs_mount "/var/db/zed/cluster", into: "/var/db/zed/cluster", mode: :ro
    end

    cluster :demo do
      cookie {:secret, :beam_cookie}

      members [
        :"hello_beam@10.17.89.95",
        :"hello_beam@10.17.89.96"
      ]
    end
  end
end
